# Generated by Django 5.1.4 on 2024-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active_now',
            field=models.BooleanField(default=False),
        ),
    ]
