# Generated by Django 5.1.4 on 2024-12-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderitem_purchaser_ordermaker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordermaker',
        ),
        migrations.AddField(
            model_name='order',
            name='order_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderMaker',
        ),
    ]
