# Generated by Django 5.1.4 on 2024-12-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_orderitem_ordermaker_order_order_maker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='primary_unit',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='secondary_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='secondary_unit',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='primary_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
