# Generated by Django 5.1.4 on 2024-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_orderitem_primary_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmessage',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
