# Generated by Django 5.1.4 on 2024-12-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderitemmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmessage',
            name='receiving_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='orderitemmessage',
            name='sending_user',
        ),
        migrations.AddField(
            model_name='orderitemmessage',
            name='sending_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
