# Generated by Django 5.1.4 on 2024-12-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderitemmessage_receiving_user'),
    ]

    operations = [
    ]
