# Generated by Django 5.1.4 on 2024-12-18 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20241218_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmessagenotification',
            name='order_item_message',
        ),
        migrations.RemoveField(
            model_name='orderitemmessagenotification',
            name='receiving_user',
        ),
        migrations.RemoveField(
            model_name='orderitemmessagenotification',
            name='sending_user',
        ),
        migrations.AddField(
            model_name='orderitemmessagenotification',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitemmessagenotification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitemmessagenotification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemmessagenotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
