# Generated by Django 5.1.4 on 2024-12-18 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_orderitemmessagenotification_order_item_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_shops', to='api.shop'),
        ),
    ]
