# Generated by Django 5.1.4 on 2024-12-19 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderitem_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to=settings.AUTH_USER_MODEL),
        ),
    ]
