# Generated by Django 5.1.4 on 2024-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_now',
            field=models.BooleanField(default=False),
        ),
    ]
