# Generated by Django 5.1.4 on 2024-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_is_active_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bg_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='text_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
